donasinontunai/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = 'donasinontunai'

urlpatterns = [
    path('donasi_nontunai/', views.donasi_nontunai, name='donasi_nontunai'),
    path('list_donasinontunai/', views.list_donasinontunai, name='list_donasinontunai'),
    path('donasi_nontunai/posts/', views.posts, name='posts'),
]

tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('pertanyaan.urls')),
    path('donasi_tunai/',include('donasi1.urls'),name='donasi1'),
    path('', include('donasinontunai.urls')),
    path('', include('user.urls'))
]

donasinontunai/models.py
from django.db import models

# Create your models here.
class DonasiNonTunai(models.Model):
	nama = models.CharField('Nama', max_length = 120)
	alamat = models.TextField('Alamat')
	kontak = models.CharField('Email atau Nomor Handphone', max_length = 120)
	kebutuhan1 = models.CharField('Kebutuhan Logistik', max_length = 120)
	kebutuhan2 = models.CharField('Kebutuhan Lainnya(Optional)', max_length = 120, blank=True, default='')
	anon = models.BooleanField('Tampilkan sebagai Donatur Anonim', default = False)

donasinontunai/forms.py
from django import forms
from .models import DonasiNonTunai

class DonasiNonTunaiForm(forms.ModelForm):
    class Meta:
        model = DonasiNonTunai
        fields = '__all__'
        

donasinontunai/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers
from .models import DonasiNonTunai
from .forms import DonasiNonTunaiForm
# Create your views here.

def donasi_nontunai(request):
    submitted = False
    if request.method == 'POST' :
        form = DonasiNonTunaiForm(request.POST)
        form.save()
        return HttpResponseRedirect('/donasi_nontunai/?submitted=True')
    else :
        form = DonasiNonTunaiForm()
        if 'submitted' in request.GET :
            submitted = True
        context = {'form' : form, 'submitted' : submitted}  

    return render(request, 'form_donasinontunai.html', context)    

def list_donasinontunai(request):
    donatur = DonasiNonTunai.objects.all()
    context = {'donatur' : donatur}
    return render(request, 'list_donasinontunai.html', context)     

def posts(request):
    q = request.GET.get('q')
    posts = DonasiNonTunai.objects.filter(nama__icontains = q)
    post_list = serializers.serialize('json', posts)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

donasinontunai/templates/form_donasinontunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Donasi Non Tunai</title>
{% endblock meta %}

{% block content %}
  <div class="content mt-5 pt-5">
  {% if submitted %}
  <div class="make_center">
  	<h1 class="title">Donasi Anda Sudah Terdata!</h1>
  	<a href="/main" class="btn">Kembali ke Halaman Utama</a>
  	<a href="{% url 'donasinontunai:list_donasinontunai' %}" class="btn">Daftar Donatur</a>
  </div>
  
  {% else %}
    <h1 class="title">Form Donasi Non Tunai<br></h1>
  	<div class="form mt-5">
      {% if user.is_authenticated %}
  		<form action="" method="POST">
		  {% csrf_token %}
        <p>Nama:</p>
        <p>{{form.nama}}</p>
        <p>Alamat:</p>
	    	<p>{{ form.alamat }}</p>
        <p>Email atau No. Handphone:</p>
        <p>{{form.kontak}}</p>
        <p>Kebutuhan Logistik</p>
        <p>{{form.kebutuhan1}}</p>
        <p>Kebutuhan Lainnya(Optional)</p>
        <p>{{form.kebutuhan2}}</p>
        <p>{{form.anon}} Tampilkan sebagai donatur anonim</p>
        <br>
        <h2 class="content_list" style="text-align: center; color: #272343"><strong>Setelah mengisi form ini, <br>
          mohon konfirmasi ke kontak<br>
          di bawah ini:<br></strong></h2>
        <h2 class="content_list" style="text-align: center; color: #272343">Budi / +62 0812345678<br></h2>
        <input type="submit" value="Kirim" class="btn mt-5">
        <a href="{% url 'donasinontunai:list_donasinontunai' %}" class="btn mt-5">Daftar Donatur</a>
		</form>
    </div>
    {% else %}
    <div class="container">
      <div class="row text-center">
        <div class="col">
          <h3>Ingin berdonasi? Silahkan <a href="/accounts/login">Login </a>atau <a href="/signup">Signup </a>terlebih dahulu!</h3>
        </div>
      </div>
      <div class="row text-center">
        <div class="col">
          <a href="{% url 'donasinontunai:list_donasinontunai' %}" class="btn mt-5">Daftar Donatur</a>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
  {% endif %}
{% endblock content %}

donasinontunai/templates/list_donasinontunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Donatur</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Daftar Donatur</h1>
	<!-- <div class="container mt-5">
		<div class="row">
			<table class="table table-borderless text-center">
				<tr>
					<th scope="col">No</th>
					<th scope="col">Nama</th>
					<th scope="col">Kebutuhan Logistik</th>
					<th scope="col">Kebutuhan Lainnya(Optional)</th>
				</tr>
				{% for x in donatur %}
				{% if x.anon %}
				<tr>
					<td scope="row">{{forloop.counter}}</th>
					<td>Anonim</td>
					<td>{{x.kebutuhan1}}</td>
					<td>{{x.kebutuhan2}}</td>
				</tr>
				{% else %}
				<tr>
					<td scope="row">{{forloop.counter}}</th>
					<td>{{x.nama}}</td>
					<td>{{x.kebutuhan1}}</td>
					<td>{{x.kebutuhan2}}</td>
				</tr>
				{% endif %}
				{% endfor %}
			</table>
	    <a href="/donasi_nontunai" class="btn mt-5">Kembali ke Form Donasi Non Tunai</a>
		</div>
		
	</div> -->
	<div class="container pt-5">
		<input id="input" class="mb-5" placeholder="Search">
	  
		<table id="result" class="table table-borderless text-center">
			<tr>
				<th scope="col">No</th>
				<th scope="col">Nama</th>
				<th scope="col">Kebutuhan Logistik</th>
				<th scope="col">Kebutuhan Lainnya(Optional)</th>
			</tr>
		
		</table>
	</div>

	<script>
	$(document).ready( function() {
    url_default = '/donasi_nontunai/posts/?q=';
    $.ajax({
      	url: url_default,
      	success: function(tmp) {
		var obj_default = $('#result');
		
        for (i = 0; i < tmp.length; i++) {
			if (tmp[i].fields.anon == true) {
          		var def_kebutuhan1 = tmp[i].fields.kebutuhan1;
         		var def_kebutuhan2 = tmp[i].fields.kebutuhan2;
          		obj_default.append('<tr> <td> ' + (i+1) + '</td> <td>' + 'Anonim' + '</td> <td>' + def_kebutuhan1 + '</td> <td>' + def_kebutuhan2 +' </td>');
        	} else {
				var def_nama = tmp[i].fields.nama;
          		var def_kebutuhan1 = tmp[i].fields.kebutuhan1;
         		var def_kebutuhan2 = tmp[i].fields.kebutuhan2;
          		obj_default.append('<tr> <td> ' + (i+1) + '</td> <td>' + def_nama + '</td> <td>' + def_kebutuhan1 + '</td> <td>' + def_kebutuhan2 +' </td>');
			}
		}
          		
      	}
    	})
	  })
	$("#input").keyup( function(e) {
    var content = $("#input").val();
    var url_res = '/donasi_nontunai/posts/?q=' + content;
  
    $.ajax({
      url: url_res,
      success: function(result) {
		var obj_result = $("#result");
		obj_result.empty();
		obj_result.append('<tr> <th> ' + 'No' + '</th> <th>' + 'Nama' + '</th> <th>' + 'Kebutuhan Logistik' + '</th> <th>' + 'Kebutuhan Lainnya(Optional)' + '</th>')

        for (i = 0; i < result.length; i++) {
			if (result[i].fields.anon == true) {
      			var kebutuhan1 = result[i].fields.kebutuhan1;
         		var kebutuhan2 = result[i].fields.kebutuhan2;
          		obj_result.append('<tr> <td> ' + (i+1) + '</td> <td>' + 'Anonim' + '</td> <td>' + kebutuhan1 + '</td> <td>' + kebutuhan2 +' </td>');
			} else {
				var nama = result[i].fields.nama;
				var kebutuhan1 = result[i].fields.kebutuhan1;
         		var kebutuhan2 = result[i].fields.kebutuhan2;
          		obj_result.append('<tr> <td> ' + (i+1) + '</td> <td>' + nama + '</td> <td>' + kebutuhan1 + '</td> <td>' + kebutuhan2 +' </td>');
			}
			
        }
    	}
    })
  	})
	</script>
  		
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
{% endblock content %}