pertanyaan/urls.py
from django.urls import path
from . import views

app_name = 'pertanyaan'

urlpatterns = [
	path('asked_us/', views.asked_us, name='asked_us'),
	path('list_asked/', views.list_asked, name='list_asked'),
	path('search/', views.search, name='search')
]

tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('pertanyaan.urls')),
    path('donasi_tunai/',include('donasi1.urls'),name='donasi1'),
    path('', include('donasinontunai.urls')),
    path('', include('user.urls'))
]

pertanyaan/models.py
from django.db import models

# Create your models here.
class Pertanyaan(models.Model):
	nama = models.CharField('Nama', max_length=120)
	kontak = models.CharField('Email atau Nomor Handphone', max_length=120)
	pertanyaan = models.CharField('Pertanyaan', max_length=1000)

pertanyaan/forms.py
from django import forms
from .models import Pertanyaan

class Form (forms.ModelForm):
	class Meta:
		model = Pertanyaan
		fields = '__all__'

		error_messages={
			'required':'Please type'
		}

pertanyaan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from .forms import Form
from .models import Pertanyaan
from django.contrib.auth.decorators import login_required
import json

@login_required
def asked_us(request):
	form = Form(request.POST or None)
	data={}
	if request.is_ajax():
		if form.is_valid():
			form.save()
			data['nama'] = form.cleaned_data.get('nama')
			data['kontak'] =form.cleaned_data.get('kontak')
			data['pertanyaan'] =form.cleaned_data.get('pertanyaan')
			return JsonResponse(data)
	return render(request, 'form_pertanyaan.html', {'form' : form})

@login_required
def list_asked(request):
	mylist = Pertanyaan.objects.all()
	return render(request, 'list_result.html', {'mylist':mylist})

def search(request):
	q = request.GET.get('q')
	posts = Pertanyaan.objects.filter(pertanyaan__icontains = q)
	mylist = serializers.serialize('json', posts)
	return HttpResponse(mylist, content_type="text/json-comment-filtered")

pertanyaan/templates/form_pertanyaan.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
<title>Form Pertanyaan</title>
{% endblock meta %}

{% block content %}
  <div class="content mt-5 pt-5">
    <h1 class="title">Pertanyaan</h1>
    <div id="alert-box"></div>
    <div class="form" id="myform">
      <form action="" method="POST" autocomplete="off">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn">Kirim</button>
        <a href="{% url 'pertanyaan:list_asked' %}" class="btn">Daftar Pertanyaan</a>
      </form>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script src="{% static 'js/pertanyaan_form.js' %}"></script>
{% endblock %}

pertanyaan/templates/list_result.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Pertanyaan</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Daftar Pertanyaan</h1>
	<div class="make_center">
		<div class="ui-widget">
			<label><b>Cari Pertanyaan disini : </b></label>
			<input id="places"/>
		</div>  
	</div>
	<div class="make_center">
		<dl class="accordion">
	  		{% for i in mylist %}
			<div class="accordion-content">
	  			<dt class="d-flex justify-content-between">
			  		<a><b>{{i.pertanyaan}}</b></a>
		  		</dt>
		  		<dd>
		  			<p><b>Penulis : </b>{{i.nama}}</p>
		  		</dd>
		  	</div>
		    {% endfor %}
	    </dl>
	    <a href="/faq" class="btn">Kembali ke FAQ</a>
	</div>

	
</div>
{% endblock content %}

{% block script %}
	<script src="{% static 'js/pertanyaan_result.js' %}"></script>
{% endblock %}