main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('infografis/', views.infografis, name='infografis'),
    path('faq/', views.faq, name='faq')
]

tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('pertanyaan.urls')),
    path('donasi_tunai/',include('donasi1.urls'),name='donasi1'),
    path('', include('donasinontunai.urls')),
    path('', include('user.urls'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS Bootstrap -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- JQUI -->
  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
  <!-- CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-custom">
    <div class="container">
    <a class="navbar-brand" href="{% url 'main:home' %}">TK2</a>
    <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <!-- <a class="nav-item nav-link page-scroll" href="#home">Home <span class="sr-only">(current)</span></a> -->
        <a class="nav-item nav-link" href="{% url 'main:home' %}">Home</a>
        <a class="nav-item nav-link" href="#contact">Contact</a>
        <a class="nav-item nav-link">|</a>
        {% if user.is_authenticated %}
          <a class="nav-item nav-link">Hi, {{user.username}} !</a>
          <a class="nav-item nav-link" href="/logout" name="logout">Log Out</a>
        {% else %}
          <a href="/accounts/login" class="nav-item nav-link" name="login">Login</a>
          <a href="/signup" class="nav-item nav-link" name="signup">Sign Up</a>
        {% endif %}
      </div>
    </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <br><br>
  <div class="footer">
      <div class="flex_footer">
        <div class="contact_us" id="contact">
          <p>Contact Us</p>
          <p><img src="{% static 'img/phone.png' %}">	+62 8213 9003 9865</p>
        </div>
        <div>
          <p><a href="/faq">FAQ</a></p>
          <p><a href="">Kritik & Saran</a></p>
        </div>
      </div>
        <p class="make_center">Copyright Kelompok D04 Reserved</p>
  </div>
  {% block script %}{% endblock %}
</body>

</html>