donasi1/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = 'donasi1'

urlpatterns = [
    path('', views.donasi_tunai, name='donasi_tunai'),
	path('list_donasitunai/', views.list_donasitunai, name='list_donasitunai'),
    path('posts/', views.posts, name='posts'),
]

tk2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('',include('pertanyaan.urls')),
    path('donasi_tunai/',include('donasi1.urls'),name='donasi1'),
    path('', include('donasinontunai.urls')),
    path('', include('user.urls'))
]

donasi1/models.py
from django.db import models

# Create your models here.
class DonasiTunai(models.Model):
	nama = models.CharField('Nama', max_length=120)
	alamat = models.TextField('Alamat')
	kontak = models.CharField('Email atau No. Handphone', max_length=100)
	jumlah = models.CharField('Jumlah Transfer', max_length=50)
	anon = models.BooleanField('Tampilkan sebagai donatur anonim', default=False)

donasi1/forms.py
from django import forms
from .models import DonasiTunai

# Create your views here.
class DonasiTunaiForm(forms.ModelForm):
    class Meta:
        model = DonasiTunai
        fields = {'nama', 'alamat', 'kontak', 'jumlah', 'anon'}

        widgets = {
            'nama': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'Nama Donatur',
                'required':True}),
            'alamat': forms.Textarea(attrs={
                'class':'form-control',
                'placeholder':'Alamat Donatur',
                'required':True}),
            'kontak': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'e.g.: contoh@email.com / 0213427253',
                'required':True}),
            'jumlah': forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':'e.g.: Rp10.000',
                'required':True}),
        }

donasi1/views.py
from django.shortcuts import render,redirect
from .forms import DonasiTunaiForm
from .models import DonasiTunai
from django.core import serializers
from django.http import HttpResponse

# Create your views here.
def donasi_tunai(request):
    if request.method == "POST":
        form = DonasiTunaiForm(request.POST or None)
        if form.is_valid:
            form.save()
        return redirect('/donasi_tunai/list_donasitunai')
    else:
        form = DonasiTunaiForm()
        response = {'form' : form}
    return render(request, 'form_donasitunai.html', response)

def list_donasitunai(request):
    donatur = DonasiTunai.objects.all()
    response = {'donatur':donatur}
    return render(request, 'list_donasitunai.html', response)

def posts(request):
    q = request.GET.get('q')
    posts = DonasiTunai.objects.filter(nama__icontains = q)
    post_list = serializers.serialize('json', posts)
    return HttpResponse(post_list, content_type="text/json-comment-filtered")

donasi1/templates/form_donasitunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Donasi Tunai</title>
{% endblock meta %}

{% block content %}
  <div class="content mt-5 pt-5">
    {% if user.is_authenticated %}
    <h1 class="title">Form Donasi Tunai<br></h1>
  	<div class="form">
  		<form action="" method="POST">
        <h2 class="content_list" style="text-align: center; color: #272343"><strong>Harap mentransfer donasi ke salah satu rekening di bawah ini:</h2>
          <div id="accordion">
            <h3 class="content_list" style="text-align: center; color: #272343">Bank ABC</h3>
            <div>
              <p>
                No. Rekening: 1823639283 a/n Andi
              </p>
            </div>
            <h3 class="content_list" style="text-align: center; color: #272343">Bank DEF</h3>
            <div>
              <p>
                No. Rekening: 278913721823 a/n Dina
              </p>
            </div>
            <h3 class="content_list" style="text-align: center; color: #272343">Bank GHI</h3>
            <div>
              <p>
                No. Rekening: 1378912312 a/n Gina
              </p>
            </div>
          </div>
          <br>
			{% csrf_token %}
        <p>Nama:</p>
        <p>{{form.nama}}</p>
        <p>Alamat:</p>
	    	<p>{{ form.alamat }}</p>
        <p>Email atau No. Handphone:</p>
        <p>{{form.kontak}}</p>
        <p>Jumlah Transfer</p>
        <p>{{form.jumlah}}</p>
        <p>{{form.anon}} Tampilkan sebagai donatur anonim</p>
        <br>
        <h2 class="content_list" style="text-align: center; color: #272343"><strong>Jika sudah mengisi form diatas, <br>
          mohon konfirmasi ke kontak<br>
          di bawah ini:<br></strong>Budi / +62 0812345678<br></h2>
        <input type="submit" value="Kirim" class="btn">
        <a href="{% url 'donasi1:list_donasitunai' %}" class="btn">Daftar Donatur</a>
		</form>
    </div>
    {% else %}
    <div style="text-align: center;">
    <h3>Ingin berdonasi? Silahkan <a href="/accounts/login">Login </a>atau <a href="/signup">Signup </a>terlebih dahulu!</h3>
    <br>
    <h3><a href="{% url 'donasi1:list_donasitunai' %}">Daftar Donatur</a></h3>
    </div>
    {% endif %}
  </div>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    $(document).ready(function(){
      $( function() {
        $( "#accordion" ).accordion();
      } );
  
      $( "h3" ).hover(
        function() {
        $( this ).append( $( "<span> ***</span>" ) );
      }, function() {
        $( this ).find( "span" ).last().remove();
      }
    );
  });
  </script>
{% endblock content %}

donasi1/templates/list_donasitunai.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Daftar Donatur</title>
{% endblock meta %}

{% block content %}
<div class="content mt-5 pt-5">
	<h1 class="title">Daftar Donatur</h1>
	<div class="input">
		<input type="text" id="input" placeholder="search..." title="search">
		<table class= "table" style="font-family: 'Roboto'; color: #272343 ">
			<thead>
				<tr>
					<th scope="col" class="align-middle" style="font-family: 'Roboto'" >nama</th>
					<th scope="col" class="align-middle" style="font-family: 'Roboto'">jumlah</th>
				</tr>
			</thead>
			<tbody id="konten"></tbody>
		</table>
	</div>

	<a href="/donasi_tunai" class="btn">Kembali ke Form Donasi Tunai</a>
</div>
<script>
	 $("#input").on("keyup", function(e) {
		var q = $(this).val();
		console.log("masuk");
        $.ajax({
				url: "/donasi_tunai/posts/?q=" + q,
        success: function(data) {
				console.log("test")
				console.log(data)
				$('#konten').html('')
				var result= '<tr>';
        for (var i = 0; i < data.length; i++) {
          console.log(data[i])
          console.log("---------")
          if (data[i].fields.anon != true){
          result += "<tr>" +
						"<td class='align-middle'>" + data[i].fields.nama + "</td>" +
            "<td class='align-middle'>" + data[i].fields.jumlah + "</td>" 
          }else{
            result += "<tr>" +
						"<td class='align-middle'>" + "Anonim" + "</td>" +
            "<td class='align-middle'>" + data[i].fields.jumlah + "</td>" 
          }
				}
				$('#konten').append(result);
      },
        })
	});
</script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
{% endblock content %}
 